# Site Settings
baseurl: ""
url : "https://estebmaister.github.io"

# Blog Settings
theme_settings :
  title : Estebmaister
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Esteban Camargo
    description : creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 2020-08-03
        end : 2023-05-06
        experience : Encora, Full Stack Dev
    skills : 
      - skill : Golang
        value : 95  # Percent value
      - skill : Java
        value : 85
      - skill : Node
        value : 90
      - skill : Python
        value : 90
      - skill : JS, HTML & CSS
        value : 90
  # Icons
  icons :
    email:    estebmaister@gmail.com
    linkedin: https://linkedin.com/in/estebmaister
    github:   estebmaister
    twitter:   estebmaister
    youtube:   estebmaister
    facebook:  estebmaister
    instagram: estebmaister
    gitlab: 
    bitbucket: 
    google_plus:

  # Disqus
  disqus_shortname: esteb

# Pagination
paginate: 6
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
