# Site Settings
baseurl: ""
url : "https://estebmaister.github.io"

# Blog Settings
theme_settings :
  title : Estebmaister
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Esteban Camargo
    description : Web developer, enthusiastic programmer, and chemical engineer from the USB. Organized, disciplined and able to solve problems in stress situations are elements that make me stand out. <br> Passionate about adventure sports and former president of the university hiking group 'Oikos'
    curriculum : https://estebmaister.github.io/curriculum
    experience :
      - start : 2017-09
        end : 2019-10
        experience : Freelance, Fullstack Dev
      - start : 2020-01
        end : 2021-01
        experience : Trulocal, Backend Dev
      - start : 2021-01
        end : 2021-08
        experience : SpiderOak, Golang Dev
      - start : 2021-08
        end : 2023
        experience : Encora, Fullstack Dev
      - start : 2021-08
        end : 2023
        experience : Cision, Contractor developer
    skills : 
      - skill : "Preferred language: Golang"
        value : 95  # Percent value
      - skill : "Backends: Java (Springboot), Node & Python"
        value : 90
      - skill : "Frontend: React, JS, HTML & CSS"
        value : 90
      - skill : ElasticSearch, PostgreSQL, MongoDB, CouchDB & Redis
        value : 90
      - skill : "Queues: Kafka & NSQ"
        value : 80
  # Icons
  icons :
    github:    estebmaister
    instagram: estebmaister
    twitter:   estebmaister
    facebook:  estebmaister
    youtube:   estebmaister
    linkedin:  https://linkedin.com/in/estebmaister
    #email:    estebmaister@gmail.com
    gitlab: 
    bitbucket: 
    google_plus:

  # Disqus
  disqus_shortname: esteb

# Pagination
paginate: 6
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
